import type { Metadata } from "next";
import { Unbounded } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import SPWProvider from "@/components/providers/SPWProvider";

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${unbounded.variable} antialiased text-[#F9F8FC]`}
      >
        <SPWProvider>
          <Header />
          <main className="pt-[85px] px-6">
            <div className="pt-4">
              {children}
            </div>
          </main>
        </SPWProvider>
      </body>
    </html>
  );
}
