import type { Metadata } from "next";
import { Unbounded } from "next/font/google";
import "./globals.css";
import SPWProvider from "@/components/providers/SPWProvider";
import { WalletModalProvider } from "@/contexts/WalletModalContext";
import ClientLayout from "@/components/layout/ClientLayout";

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Yandex.Metrika counter */}
        <script type="text/javascript" dangerouslySetInnerHTML={{
          __html: `
            (function(m,e,t,r,i,k,a){
              m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
              m[i].l=1*new Date();
              for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
              k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)
            })(window, document,'script','https://mc.yandex.ru/metrika/tag.js?id=103901262', 'ym');
            
            ym(103901262, 'init', {ssr:true, webvisor:true, clickmap:true, ecommerce:"dataLayer", accurateTrackBounce:true, trackLinks:true});
          `
        }} />
        {/* /Yandex.Metrika counter */}
      </head>
      <body
        className={`${unbounded.variable} antialiased text-[#F9F8FC]`}
      >
        <noscript>
          <div>
            <img src="https://mc.yandex.ru/watch/103901262" style={{position: 'absolute', left: '-9999px'}} alt="" />
          </div>
        </noscript>
        <SPWProvider>
          <WalletModalProvider>
            <ClientLayout>
              {children}
            </ClientLayout>
          </WalletModalProvider>
        </SPWProvider>
      </body>
    </html>
  );
}
